services:
  client:
    build:
      context: client
      args:
        VITE_DOMAIN_NAME: ${DOMAIN_SERVER_NAME}
        VITE_SESSION_TIMEOUT: ${SESSION_TIMEOUT}
    ports:
      - '80:80'
    environment:
      DOMAIN_SERVER_NAME: ${DOMAIN_SERVER_NAME}
      SERVER_URL_PROXY: http://server:8080/api/
    volumes:
      - ./client/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    networks:
      - app_network
    depends_on:
      server:
        condition: service_healthy

  server:
    build: server
    container_name: server
    ports:
      - '8080:8080'
    environment:
      DOMAIN_URL: http://${DOMAIN_SERVER_NAME}
      SERVER_DB_URL: jdbc:postgresql://server_db:5432/server_db
      SERVER_DB_USER: ${SERVER_DB_USER}
      SERVER_DB_PASSWORD: ${SERVER_DB_PASSWORD}

      SERVER_TEMP_DB_HOST: server_temp_db
      SERVER_TEMP_DB_PORT: 6379
      SERVER_TEMP_DB_PASSWORD: ${SERVER_TEMP_DB_PASSWORD}

      SESSION_TIMEOUT: ${SESSION_TIMEOUT}

      LABYRINTH_MAX_DEVICE_INACTIVITY: ${LABYRINTH_MAX_DEVICE_INACTIVITY}

      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    depends_on:
      server_db:
        condition: service_healthy
      server_temp_db:
        condition: service_healthy
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://server:8080/actuator/health" ]
      interval: 10s
      timeout: 2s
      retries: 10

  server_db:
    container_name: server_db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: server_db
      POSTGRES_USER: ${SERVER_DB_USER}
      POSTGRES_PASSWORD: ${SERVER_DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - app_network
    healthcheck:
      test: pg_isready -U postgres -d server_db
      interval: 2s
      timeout: 2s
      retries: 20

  server_temp_db:
    container_name: server_temp_db
    image:
      redis:7.4-alpine
    command: ["redis-server", "--requirepass", "${SERVER_TEMP_DB_PASSWORD}"]
    ports:
      - '6379:6379'
    volumes:
      - redis_db:/data
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${SERVER_TEMP_DB_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  db:
  redis_db:

networks:
  app_network: