version: "3.8"

services:
  server_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - network_server_db
    healthcheck:
      test: pg_isready -U postgres -d server
      interval: 2s
      timeout: 2s
      retries: 20

  temporary_message_storage:
    image:
      redis:7.4-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_db:/data

volumes:
  db:
  redis_db:

networks:
  network_server_db: