services:
  #  TODO: setup client

  server:
    build: server
    ports:
      - '8080:8080'
    environment:
      POSTGRES_HOST: server_db
      POSTGRES_PORT: 5432
      REDIS_HOST: temporary_message_storage
      REDIS_PORT: 6379
    depends_on:
      - server_db
      - temporary_message_storage
    networks:
      - network_server_db

  server_db:
    container_name: server_db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - network_server_db
    healthcheck:
      test: pg_isready -U postgres -d server
      interval: 2s
      timeout: 2s
      retries: 20

  temporary_message_storage:
    container_name: temporary_message_storage
    image:
      redis:7.4-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_db:/data
    networks:
      - network_server_db

volumes:
  db:
  redis_db:

networks:
  network_server_db: