app:
  labyrinth:
    max-device-inactivity-seconds: 86400

logging:
  level:
    org.springframework:
      security: DEBUG
      web: DEBUG
    edu.pw.chat: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/server
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

server:
  servlet:
    session:
      timeout: 60m
      cookie:
        same-site: strict
        http-only: true
        path: "/api/"
        name: "SESSION"
        secure: false # TODO: Change after adding secure TLS support
