app:
  labyrinth:
    max-device-inactivity: ${LABYRINTH_MAX_DEVICE_INACTIVITY}

logging:
  level:
    org.springframework:
      security: DEBUG
      web: DEBUG
    edu.pw.chat: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://${SERVER_DB_HOST}:${SERVER_DB_PORT}/${SERVER_DB_NAME}
    username: ${SERVER_DB_USER}
    password: ${SERVER_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

server:
  servlet:
    session:
      timeout: 60m
      cookie:
        same-site: strict
        http-only: true
        path: "/api/"
        name: "SESSION"
        secure: false # TODO: Change after adding secure TLS support
