app:
  labyrinth:
    max-device-inactivity: ${LABYRINTH_MAX_DEVICE_INACTIVITY}
  client:
    url: ${DOMAIN_URL}
  temp-db:
    host: ${SERVER_TEMP_DB_HOST}
    port: ${SERVER_TEMP_DB_PORT}
    password: ${SERVER_TEMP_DB_PASSWORD}

spring:
  datasource:
    url: ${SERVER_DB_URL}
    username: ${SERVER_DB_USER}
    password: ${SERVER_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
  data:
    jdbc:
      dialect: postgresql # Todo: remove

server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT}
      cookie:
        same-site: strict
        http-only: true
        path: "/api/"
        name: "SESSION"
        secure: false # TODO: Change after adding secure TLS support
