spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/server
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop