name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Image
        run: docker compose -f compose.yml build server

      - name: Build Frontend Image
        run: docker compose -f compose.yml build client

      - name: Verify Built Images
        run: docker images

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start Full Stack Services
        run: docker compose -f compose.yml --env-file .env.test up --build -d

      - name: Wait for Services to Be Ready
        run: sleep 100

      - name: Run Cypress Tests
        working-directory: ./client
        run: npx cypress run

      - name: Stop Services
        run: docker compose -f compose.yml down
