name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start Full Stack Services
        run: docker compose -f compose.yml --env-file .env.test up --build -d

      - name: Run Cypress Tests
        working-directory: ./client
        run: npm i; npx cypress run

      - name: Stop Services
        run: docker compose -f compose.yml down
